### ISSUE TITLE
When I go look for group it shows someone els steam profile

### ISSUE THREAD

**Issue by MarieCherry** [Karechta/looking_for_gs#10]
When I go LFG, it show someone els profile is this a bug?
![Screenshot 2023-03-01 065103](https://user-images.githubusercontent.com/126625367/221999598-23085d33-4137-42da-aacc-7c88bcc20bf1.png)

**Comment by MarieCherry** [comment]
Here you can see no one is in my group and it show there is another player in my group
![Screenshot 2023-03-01 065854](https://user-images.githubusercontent.com/126625367/222000910-dea0cf9d-6411-45ae-9242-ed8fbb258967.png)

**Comment by Karechta** [comment]
looks like you were in a lobby with jezza, when leaving his Lobby, it just didnt show the join button, as it was rendered beforehand.
Not sure if thats exactly the problem.
I cannot look into it though, since I do not intend to buy a subscription.
