### ISSUE TITLE
I don't see anyone in search

### ISSUE THREAD

**Issue by ghost** [Karechta/looking_for_gs#7]
Hello, when my friend try to look for the legit hacking or anything else, i don't see him in gs looking to play (also when i try to look my friend don't see me tho), do you know any way how to fix this? Thanks

**Comment by Karechta** [comment]
Hi, are you getting any errors in the console? 
Can you see the looking for gamesense tab and it just doesnt show any players? 
Also, did you try disabling other lua scripts to see if there might be some incompatible ones
Maybe some errors when trying to "look for Legit" or smthg
You can hit me up on Discord #Karechta3979

**Comment by ghost** [comment]
Oh, it started working idk what was it, maybe im just retard, buy thanks for help!
